/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Professor_UI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.professor.ProfessorAccount;
import model.professor.ProfessorDirectory;
import model.course.Courses;
import model.course.CourseDirectory;

/**
 *
 * @author Donald Mucharla
 */
public class ProfessorFirst extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorFirst
     */
    private ProfessorDirectory professorDirectory;
    private CourseDirectory coursesdirectory;
    public ProfessorFirst(ProfessorDirectory professorDirectory, CourseDirectory coursesdirectory) {
        initComponents();
        this.professorDirectory = professorDirectory;
        this.coursesdirectory= coursesdirectory;
    }

    

   

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ProfessorLogin = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProfessorunameL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ProfessorpasswordL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        ProfessorCreateAccount = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        AgeprofessorC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CountryprofessorC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LanguageprofessorC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BloodprofessorC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FnameprofessorC = new javax.swing.JTextField();
        LnameprofessorC = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ProfessorHomepage = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        Grades = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtGradeP = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Edit = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtcourseTitle = new javax.swing.JTextField();
        txtsubjectcode = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtTerm = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtclassTime = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtcredits = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtModules = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        AddCourse = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtcourseTitle1 = new javax.swing.JTextField();
        txtModules1 = new javax.swing.JTextField();
        txtsubjectcode1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtLanguage1 = new javax.swing.JTextField();
        txtTerm1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        txtclassTime1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtcredits1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        viewProfile = new javax.swing.JPanel();
        LnameprofessorC1 = new javax.swing.JTextField();
        CountryprofessorC1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        LanguageprofessorC1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        BloodprofessorC1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        AgeprofessorC1 = new javax.swing.JTextField();
        FnameprofessorC1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        txtUname = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel29.setText("Course Title:");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        ProfessorLogin.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton1.setText("Login");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Professor Login");

        jLabel3.setText("Username :");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ProfessorunameL.setToolTipText("Please enter your username here");
        ProfessorunameL.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        ProfessorunameL.setSelectionColor(new java.awt.Color(224, 25, 44));

        jLabel4.setText("Password:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ProfessorpasswordL.setToolTipText("please enter your password here");

        jLabel5.setText("New here?");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jToggleButton2.setText("Signup");
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled-banner.png"))); // NOI18N

        javax.swing.GroupLayout ProfessorLoginLayout = new javax.swing.GroupLayout(ProfessorLogin);
        ProfessorLogin.setLayout(ProfessorLoginLayout);
        ProfessorLoginLayout.setHorizontalGroup(
            ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ProfessorLoginLayout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProfessorunameL))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProfessorpasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProfessorLoginLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jToggleButton1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLoginLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2)
                        .addGap(47, 47, 47)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProfessorLoginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jToggleButton1, jToggleButton2});

        ProfessorLoginLayout.setVerticalGroup(
            ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(110, 110, 110)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ProfessorunameL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ProfessorpasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addGap(36, 36, 36)
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jLabel5))
                .addGap(644, 644, 644))
        );

        add(ProfessorLogin, "card2");

        ProfessorCreateAccount.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Create New Account");

        AgeprofessorC.setToolTipText("enter your AGE");
        AgeprofessorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeprofessorCActionPerformed(evt);
            }
        });

        jLabel7.setText("First Name :");

        CountryprofessorC.setToolTipText("enter your COUNTRY/REGION");

        jLabel8.setText("Last Name :");

        LanguageprofessorC.setToolTipText("enter the LANGUAGE you will INSTRUCT.");

        jLabel9.setText("Age :");

        BloodprofessorC.setToolTipText("enter your BLOOD GROUP");

        jLabel10.setText("Country :");

        jToggleButton3.setText("Submit & Create Account");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Language :");

        jLabel12.setText("Blood Group:");

        FnameprofessorC.setToolTipText("enter your LEGAL FIRST NAME");
        FnameprofessorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameprofessorCActionPerformed(evt);
            }
        });

        LnameprofessorC.setToolTipText("enter your LEGAL LAST NAME");

        jLabel46.setText("Username:");

        jTextField1.setToolTipText("create a unique username for LOGGING IN");
        jTextField1.setNextFocusableComponent(jToggleButton3);

        jLabel47.setText("Password:");

        jTextField2.setToolTipText("create a strong password for LOGGING IN");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled-banner.png"))); // NOI18N

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_user.png"))); // NOI18N

        jLabel52.setText("This is a sign up page for instructors only.");

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("• Remember your CREDENTIALS which will be used to login to your account everytime.\n• If you lost your credentials then please contact ADMIN to reset your credentials.");
        jTextArea1.setToolTipText("Important Instructions");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setEnabled(false);
        jTextArea1.setFocusable(false);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout ProfessorCreateAccountLayout = new javax.swing.GroupLayout(ProfessorCreateAccount);
        ProfessorCreateAccount.setLayout(ProfessorCreateAccountLayout);
        ProfessorCreateAccountLayout.setHorizontalGroup(
            ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                .addComponent(jLabel50)
                .addGap(0, 61, Short.MAX_VALUE))
            .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgeprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CountryprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LanguageprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FnameprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LnameprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BloodprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel52)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton3)
                            .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProfessorCreateAccountLayout.setVerticalGroup(
            ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FnameprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LnameprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AgeprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CountryprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(LanguageprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(BloodprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(20, 20, 20)
                        .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton3)
                .addContainerGap(512, Short.MAX_VALUE))
        );

        jToggleButton3.getAccessibleContext().setAccessibleDescription("Make Sure all Fields are properly filled.");

        add(ProfessorCreateAccount, "card3");

        ProfessorHomepage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("YOUR COURSES");

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Term", "Class Time", "Term", "No.of Credits", "No.of Modules", "Teaching Language"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(courseTable);
        if (courseTable.getColumnModel().getColumnCount() > 0) {
            courseTable.getColumnModel().getColumn(0).setResizable(false);
            courseTable.getColumnModel().getColumn(1).setResizable(false);
            courseTable.getColumnModel().getColumn(2).setResizable(false);
            courseTable.getColumnModel().getColumn(3).setResizable(false);
            courseTable.getColumnModel().getColumn(4).setResizable(false);
            courseTable.getColumnModel().getColumn(5).setResizable(false);
            courseTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addcourse.png"))); // NOI18N
        jToggleButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton4.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggleButton4.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggleButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addcoursepressed.png"))); // NOI18N
        jToggleButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addcoursepressed.png"))); // NOI18N
        jToggleButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addcourse.png"))); // NOI18N
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("Add Course");

        jLabel17.setText("Modify Course");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modifycourse.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modifycoursepressed.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modifycoursepressed.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modifycoursepressed.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Delete Course");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_course.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_course_pressed.png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_course_pressed.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Start Grading");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grade.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setMargin(new java.awt.Insets(2, 12, 3, 14));
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grade_pressed.png"))); // NOI18N
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grade_pressed.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/viewprofile.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton7.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pressed_profile.png"))); // NOI18N
        jButton7.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pressed_profile.png"))); // NOI18N
        jButton7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/viewprofile.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled-banner.png"))); // NOI18N

        jLabel54.setText("View Profile");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabel13.setToolTipText("Log Out");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel13.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel13.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel55.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel55.setText("Course Actions:");

        javax.swing.GroupLayout ProfessorHomepageLayout = new javax.swing.GroupLayout(ProfessorHomepage);
        ProfessorHomepage.setLayout(ProfessorHomepageLayout);
        ProfessorHomepageLayout.setHorizontalGroup(
            ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                            .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfessorHomepageLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfessorHomepageLayout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                            .addComponent(jLabel55)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(250, 250, 250)
                            .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 1421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ProfessorHomepageLayout.setVerticalGroup(
            ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18))
                    .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55))
                .addGap(18, 18, 18)
                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(ProfessorHomepage, "card4");

        Grades.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("Grades");
        Grades.add(jLabel20);
        jLabel20.setBounds(447, 131, 79, 32);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "ID number", "Subject", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        Grades.add(jScrollPane2);
        jScrollPane2.setBounds(114, 181, 771, 244);

        jButton5.setText("START GRADING");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Grades.add(jButton5);
        jButton5.setBounds(680, 440, 130, 23);

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel21.setText("INSTRUCTIONS:");
        Grades.add(jLabel21);
        jLabel21.setBounds(114, 443, 147, 26);

        jLabel22.setText("Please enter the Grade:");
        Grades.add(jLabel22);
        jLabel22.setBounds(680, 480, 130, 16);
        Grades.add(txtGradeP);
        txtGradeP.setBounds(810, 480, 46, 22);

        jButton6.setText("SUBMIT GRADE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Grades.add(jButton6);
        jButton6.setBounds(740, 520, 120, 23);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButton10.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Grades.add(jButton10);
        jButton10.setBounds(22, 92, 25, 25);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled-banner.png"))); // NOI18N
        Grades.add(jLabel56);
        jLabel56.setBounds(0, 0, 1071, 74);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("⦿ Click Start Grading to Grade Students\n⦿ You should select a student from the above list first before grading");
        jTextArea2.setEnabled(false);
        jScrollPane4.setViewportView(jTextArea2);

        Grades.add(jScrollPane4);
        jScrollPane4.setBounds(114, 470, 434, 42);

        add(Grades, "card5");

        Edit.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("MODIFY COURSE");

        jLabel24.setText("Course Title:");

        txtsubjectcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubjectcodeActionPerformed(evt);
            }
        });

        jLabel25.setText("Subject Code:");

        jLabel26.setText("Term:");

        jLabel27.setText("Class Time:");

        jLabel28.setText("No.of Credits");

        jLabel30.setText("No.of Modules:");

        jLabel31.setText("Language of Instruction:");

        jButton8.setText("Save Modifications");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButton11.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled-banner.png"))); // NOI18N

        javax.swing.GroupLayout EditLayout = new javax.swing.GroupLayout(Edit);
        Edit.setLayout(EditLayout);
        EditLayout.setHorizontalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 1284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EditLayout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditLayout.createSequentialGroup()
                                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsubjectcode, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtclassTime, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcredits, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModules, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EditLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jButton8))))
                    .addGroup(EditLayout.createSequentialGroup()
                        .addGap(468, 468, 468)
                        .addComponent(jLabel23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EditLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLanguage, txtModules, txtTerm, txtclassTime, txtcourseTitle, txtcredits, txtsubjectcode});

        EditLayout.setVerticalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtcourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtsubjectcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtclassTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtcredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtModules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(635, Short.MAX_VALUE))
        );

        add(Edit, "card6");

        AddCourse.setBackground(new java.awt.Color(255, 255, 255));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setText("ADD NEW COURSE");

        jLabel33.setText("Course Title:");

        txtsubjectcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubjectcode1ActionPerformed(evt);
            }
        });

        jLabel34.setText("No.of Modules:");

        jLabel35.setText("Subject Code:");

        jLabel36.setText("Teaching Langiage:");

        jLabel37.setText("Term:");

        jButton9.setText("SAVE & ADD COURSE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel38.setText("Class Time:");

        jLabel39.setText("No.of Credits");

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled-banner.png"))); // NOI18N

        javax.swing.GroupLayout AddCourseLayout = new javax.swing.GroupLayout(AddCourse);
        AddCourse.setLayout(AddCourseLayout);
        AddCourseLayout.setHorizontalGroup(
            AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCourseLayout.createSequentialGroup()
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddCourseLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton12))
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 1385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AddCourseLayout.createSequentialGroup()
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddCourseLayout.createSequentialGroup()
                        .addGap(515, 515, 515)
                        .addComponent(jLabel32))
                    .addGroup(AddCourseLayout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsubjectcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcourseTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtclassTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcredits1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModules1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9))))
                .addGap(30, 30, 30))
        );
        AddCourseLayout.setVerticalGroup(
            AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCourseLayout.createSequentialGroup()
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(49, 49, 49)
                .addComponent(jLabel32)
                .addGap(32, 32, 32)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtcourseTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtsubjectcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtclassTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtcredits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtModules1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtLanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(131, 131, 131))
        );

        add(AddCourse, "card7");

        viewProfile.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Last Name :");

        jLabel40.setText("Age :");

        jLabel41.setText("Country :");

        jToggleButton5.setText("SAVE");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jLabel42.setText("Language :");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setText("VIEW PROFILE");

        jLabel44.setText("Blood Group:");

        AgeprofessorC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeprofessorC1ActionPerformed(evt);
            }
        });

        FnameprofessorC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameprofessorC1ActionPerformed(evt);
            }
        });

        jLabel45.setText("First Name :");

        jLabel48.setText("Username:");

        jLabel49.setText("Password:");

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled-banner.png"))); // NOI18N

        javax.swing.GroupLayout viewProfileLayout = new javax.swing.GroupLayout(viewProfile);
        viewProfile.setLayout(viewProfileLayout);
        viewProfileLayout.setHorizontalGroup(
            viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProfileLayout.createSequentialGroup()
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 1249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(viewProfileLayout.createSequentialGroup()
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewProfileLayout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel48)
                            .addComponent(jLabel16)
                            .addComponent(jLabel45)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel44))
                        .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewProfileLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jToggleButton5))
                            .addGroup(viewProfileLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LnameprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FnameprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CountryprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LanguageprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BloodprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(viewProfileLayout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addComponent(jLabel43)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewProfileLayout.setVerticalGroup(
            viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewProfileLayout.createSequentialGroup()
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(FnameprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(LnameprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(AgeprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(CountryprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(LanguageprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(BloodprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jToggleButton5)
                .addGap(97, 97, 97))
        );

        add(viewProfile, "card8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1981, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );

        add(jPanel1, "card9");
    }// </editor-fold>//GEN-END:initComponents

    private void AgeprofessorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeprofessorCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeprofessorCActionPerformed

    private void FnameprofessorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameprofessorCActionPerformed
//        ProfessorHomepage.setVisible(false);
//        AddCourse.setVisible(true);
    }//GEN-LAST:event_FnameprofessorCActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
       ProfessorHomepage.setVisible(false);
        AddCourse.setVisible(true);
        
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
    ProfessorLogin.setVisible(false);
    ProfessorCreateAccount.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String username = ProfessorunameL.getText();
        String password = ProfessorpasswordL.getText();
        ProfessorAccount professor = professorDirectory.addProfessorAccount();
        professor.setLoginusername(username);
        professor.setLoginpassword(password);
        for(ProfessorAccount p : professorDirectory.getProfessorList()){
            if(p.getUsername().equals(username) && p.getPassword().equals(password) ){
                   ProfessorLogin.setVisible(false);
                   ProfessorHomepage.setVisible(true);
                   populate();
                   JOptionPane.showMessageDialog(this, "Loged in successfully");
                   return;

            }
        }
        JOptionPane.showMessageDialog(this, "Loged failed");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtsubjectcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubjectcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubjectcodeActionPerformed

    private void txtsubjectcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubjectcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubjectcode1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRowIndex = courseTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Plese select the row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) courseTable.getModel();
        Courses selectedcouCourses =(Courses) model.getValueAt(selectedRowIndex,0);
        txtcourseTitle.setText(String.valueOf(selectedcouCourses.getCourseTitle()));
        txtsubjectcode.setText(String.valueOf(selectedcouCourses.getSubjectCode()));
        txtTerm.setText(String.valueOf(selectedcouCourses.getTerm()) );
        txtclassTime.setText(String.valueOf(selectedcouCourses.getClassTime()));
        txtcredits.setText(String.valueOf(selectedcouCourses.getNumofCredit()));
        txtModules.setText(String.valueOf(selectedcouCourses.getNumofModules()));
        txtLanguage.setText(String.valueOf(selectedcouCourses.getTeachingLanguage()));
        
        Edit.setVisible(true);
        ProfessorHomepage.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Grades.setVisible(true);
        ProfessorHomepage.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String coursetitle = txtcourseTitle1.getText();
        String subjectcode = txtsubjectcode1.getText();
        String term = txtTerm1.getText();
        String classtime = txtclassTime1.getText();
        String credithrs = txtcredits1.getText();
        String modules = txtModules1.getText();
        String language  = txtLanguage1.getText();
        String professoruname = ProfessorunameL.getText();
        Courses course = coursesdirectory.addCourse();
        course.setCourseTitle(coursetitle);
        course.setClassTime(classtime);
        course.setSubjectCode(subjectcode);
        course.setTerm(term);
        course.setNumofModules(modules);
        course.setNumofCredit(credithrs);
        course.setTeachingLanguage(language);
        course.setProfessorname(professoruname);
        JOptionPane.showMessageDialog(this,"Course added successfully");
        populate();
        txtcourseTitle1.setText("");
        txtsubjectcode1.setText("");
        txtTerm1.setText("");
        txtclassTime1.setText("");
        txtcredits1.setText("");
        txtModules1.setText("");
        txtLanguage1.setText("");
        AddCourse.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String courseTitle = txtcourseTitle.getText();
        String subjectcode = txtsubjectcode.getText();
        String term  = txtTerm.getText();
        String classtime = txtclassTime.getText();
        String credits = txtcredits.getText();
        String modules = txtModules.getText();
        String language = txtLanguage.getText();
        Courses course = coursesdirectory.addCourse();
        course.setCourseTitle(courseTitle);
        course.setSubjectCode(subjectcode);
        course.setTerm(term);
        course.setNumofCredit(credits);
        course.setNumofModules(modules);
        course.setTeachingLanguage(language);
        course.setClassTime(classtime);
        Edit.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void AgeprofessorC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeprofessorC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeprofessorC1ActionPerformed

    private void FnameprofessorC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameprofessorC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameprofessorC1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
       
       
       if(FnameprofessorC.getText().isEmpty() || LnameprofessorC.getText().isEmpty() || AgeprofessorC.getText().isEmpty() || CountryprofessorC.getText().isEmpty() || LanguageprofessorC.getText().isEmpty() || BloodprofessorC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter all the fields");
        }
        else{
            String firstName = FnameprofessorC.getText();
            String lastName = LnameprofessorC.getText();
            String age = AgeprofessorC.getText();
            String country = CountryprofessorC.getText();
            String language = LanguageprofessorC.getText();
            String bloodGtp = BloodprofessorC.getText();
            String username = jTextField1.getText();
            String password = jTextField2.getText();
            ProfessorAccount professoraccount = professorDirectory.addProfessorAccount();
            professoraccount.setFirstNamePro(firstName);
            professoraccount.setLastNamePro(lastName);
            professoraccount.setAgePro(age);
            professoraccount.setCountryPro(country);
            professoraccount.setLanguagePro(language);
            professoraccount.setBloodGroupPro(bloodGtp);
            professoraccount.setUsername(username);
            professoraccount.setPassword(password);
        
        JOptionPane.showMessageDialog(this,"Account successfully created");
        }
       FnameprofessorC.setText("");
       LnameprofessorC.setText("");
       AgeprofessorC.setText("");
       CountryprofessorC.setText("");
       LanguageprofessorC.setText("");
       BloodprofessorC.setText("");
       jTextField1.setText("");
       jTextField2.setText("");
       ProfessorCreateAccount.setVisible(false);
       ProfessorLogin.setVisible(true);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        viewProfile.setVisible(true);
        ProfessorHomepage.setVisible(false);
        displayProfile();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Grades.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Edit.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        AddCourse.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
if(FnameprofessorC.getText().isEmpty() || LnameprofessorC.getText().isEmpty() || AgeprofessorC.getText().isEmpty() || CountryprofessorC.getText().isEmpty() || LanguageprofessorC.getText().isEmpty() || BloodprofessorC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter all the fields");
        }
        else{
            String firstName = FnameprofessorC1.getText();
            String lastName = LnameprofessorC1.getText();
            String age = AgeprofessorC1.getText();
            String country = CountryprofessorC1.getText();
            String language = LanguageprofessorC1.getText();
            String bloodGtp = BloodprofessorC1.getText();
            String username = txtUname.getText();
            String password = txtpassword.getText();
  
            ProfessorAccount professoraccount = professorDirectory.addProfessorAccount();
            professoraccount.setFirstNamePro(firstName);
            professoraccount.setLastNamePro(lastName);
            professoraccount.setAgePro(age);
            professoraccount.setCountryPro(country);
            professoraccount.setLanguagePro(language);
            professoraccount.setBloodGroupPro(bloodGtp);
            professoraccount.setUsername(username);
            professoraccount.setPassword(password);
        
        JOptionPane.showMessageDialog(this,"Profile updated successfully!!");
        }
        viewProfile.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRowIndex = courseTable.getSelectedRow();
               if(selectedRowIndex<0){
                   JOptionPane.showMessageDialog(this, "Plese select the row to delete");
                   return;
               }
               DefaultTableModel model = (DefaultTableModel) courseTable.getModel();
               Courses selectedcourse =(Courses) model.getValueAt(selectedRowIndex,0);
               coursesdirectory.deleteCourse(selectedcourse);

               JOptionPane.showMessageDialog(this, "Course is deleted");
               populate();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddCourse;
    private javax.swing.JTextField AgeprofessorC;
    private javax.swing.JTextField AgeprofessorC1;
    private javax.swing.JTextField BloodprofessorC;
    private javax.swing.JTextField BloodprofessorC1;
    private javax.swing.JTextField CountryprofessorC;
    private javax.swing.JTextField CountryprofessorC1;
    private javax.swing.JPanel Edit;
    private javax.swing.JTextField FnameprofessorC;
    private javax.swing.JTextField FnameprofessorC1;
    private javax.swing.JPanel Grades;
    private javax.swing.JTextField LanguageprofessorC;
    private javax.swing.JTextField LanguageprofessorC1;
    private javax.swing.JTextField LnameprofessorC;
    private javax.swing.JTextField LnameprofessorC1;
    private javax.swing.JPanel ProfessorCreateAccount;
    private javax.swing.JPanel ProfessorHomepage;
    private javax.swing.JPanel ProfessorLogin;
    private javax.swing.JTextField ProfessorpasswordL;
    private javax.swing.JTextField ProfessorunameL;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JTextField txtGradeP;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtLanguage1;
    private javax.swing.JTextField txtModules;
    private javax.swing.JTextField txtModules1;
    private javax.swing.JTextField txtTerm;
    private javax.swing.JTextField txtTerm1;
    private javax.swing.JTextField txtUname;
    private javax.swing.JTextField txtclassTime;
    private javax.swing.JTextField txtclassTime1;
    private javax.swing.JTextField txtcourseTitle;
    private javax.swing.JTextField txtcourseTitle1;
    private javax.swing.JTextField txtcredits;
    private javax.swing.JTextField txtcredits1;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtsubjectcode;
    private javax.swing.JTextField txtsubjectcode1;
    private javax.swing.JPanel viewProfile;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        DefaultTableModel model = (DefaultTableModel) courseTable.getModel();
        model.setRowCount(0);
        for( Courses c : coursesdirectory.getCourseList()){
            if(ProfessorunameL.getText().equals(c.getProfessorname())){
                Object[] row = new Object[8];
            row[0] = c;
            row[1] = c.getTerm();
            row[2] = c.getClassTime();
            row[3] = c.getTerm();
            row[4] = c.getNumofCredit();
            row[5] = c.getNumofModules();
            row[6] = c.getTeachingLanguage();

            model.addRow(row);
            }
        }
        }

    private void displayProfile() {
        for(ProfessorAccount professor : professorDirectory.getProfessorList()){
            FnameprofessorC1.setText(professor.getFirstNamePro());
            LnameprofessorC1.setText(professor.getLastNamePro());
            AgeprofessorC1.setText(professor.getAgePro());
            CountryprofessorC1.setText(professor.getCountryPro());
            LanguageprofessorC1.setText(professor.getLanguagePro());
            BloodprofessorC1.setText(professor.getBloodGroupPro());
            txtUname.setText(professor.getUsername());
            txtpassword.setText(professor.getPassword());
                    
            
        }
        }
}
