/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Professor_UI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.professor.ProfessorAccount;
import model.professor.ProfessorDirectory;
import model.course.Courses;
import model.course.CourseDirectory;
import model.student.*;

/**
 *
 * @author Donald Mucharla
 */
public class ProfessorFirst extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorFirst
     */
    private ProfessorDirectory professorDirectory;
    private CourseDirectory coursesdirectory;
    private studentperformancecatalouge performancecatalogue;
    private choosedcoursecatalogue choosedcatalogue;
    private StudentCatalogue studentCatalogue;
    private studentperformancecatalouge performacecatalogue;
    public ProfessorFirst(ProfessorDirectory professorDirectory, CourseDirectory coursesdirectory, studentperformancecatalouge performancecatalogue, choosedcoursecatalogue choosedcatalogue, StudentCatalogue studentCatalogue, studentperformancecatalouge performacecatalogue) {
        initComponents();
        this.professorDirectory = professorDirectory;
        this.coursesdirectory= coursesdirectory;
        this.performancecatalogue = performancecatalogue;
        this.choosedcatalogue = choosedcatalogue;
        this.studentCatalogue = studentCatalogue;
        this.performacecatalogue = performacecatalogue;
    }

    

   

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ProfessorLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProfessorunameL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ProfessorpasswordL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        ProfessorCreateAccount = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        AgeprofessorC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CountryprofessorC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LanguageprofessorC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BloodprofessorC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FnameprofessorC = new javax.swing.JTextField();
        LnameprofessorC = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        ProfessorHomepage = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Grades = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gradestbl = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtGradeP = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Edit = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtcourseTitle = new javax.swing.JTextField();
        txtsubjectcode = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtTerm = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtclassTime = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtcredits = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtModules = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        AddCourse = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtcourseTitle1 = new javax.swing.JTextField();
        txtModules1 = new javax.swing.JTextField();
        txtsubjectcode1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtLanguage1 = new javax.swing.JTextField();
        txtTerm1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        txtclassTime1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtcredits1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        viewProfile = new javax.swing.JPanel();
        LnameprofessorC1 = new javax.swing.JTextField();
        CountryprofessorC1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        LanguageprofessorC1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        BloodprofessorC1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        AgeprofessorC1 = new javax.swing.JTextField();
        FnameprofessorC1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        txtUname = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        jLabel29.setText("Course Title:");

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("E-Learning Platform");

        jToggleButton1.setText("Login");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please Login");

        jLabel3.setText("Username :");

        jLabel4.setText("Password:");

        jLabel5.setText("Create new account:");

        jToggleButton2.setText("Signup");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfessorLoginLayout = new javax.swing.GroupLayout(ProfessorLogin);
        ProfessorLogin.setLayout(ProfessorLoginLayout);
        ProfessorLoginLayout.setHorizontalGroup(
            ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLoginLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
            .addGroup(ProfessorLoginLayout.createSequentialGroup()
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ProfessorpasswordL, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                .addComponent(ProfessorunameL))))
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1)
                            .addComponent(jToggleButton2))))
                .addContainerGap())
        );

        ProfessorLoginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jToggleButton1, jToggleButton2});

        ProfessorLoginLayout.setVerticalGroup(
            ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLoginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ProfessorunameL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProfessorLoginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProfessorpasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfessorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jLabel5))
                .addGap(247, 247, 247))
        );

        add(ProfessorLogin, "card2");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Create New Account");

        AgeprofessorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeprofessorCActionPerformed(evt);
            }
        });

        jLabel7.setText("First Name :");

        jLabel8.setText("Last Name :");

        jLabel9.setText("Age :");

        jLabel10.setText("Country :");

        jToggleButton3.setText("Create");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Language :");

        jLabel12.setText("Blood Group:");

        FnameprofessorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameprofessorCActionPerformed(evt);
            }
        });

        jLabel46.setText("User Name:");

        jLabel47.setText("Password:");

        javax.swing.GroupLayout ProfessorCreateAccountLayout = new javax.swing.GroupLayout(ProfessorCreateAccount);
        ProfessorCreateAccount.setLayout(ProfessorCreateAccountLayout);
        ProfessorCreateAccountLayout.setHorizontalGroup(
            ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FnameprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LnameprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CountryprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LanguageprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1)
                            .addComponent(BloodprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton3)))
                    .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel6)))
                .addGap(127, 127, 127))
        );

        ProfessorCreateAccountLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AgeprofessorC, BloodprofessorC, CountryprofessorC, FnameprofessorC, LanguageprofessorC, LnameprofessorC, jTextField1, jTextField2});

        ProfessorCreateAccountLayout.setVerticalGroup(
            ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FnameprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LnameprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AgeprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CountryprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(LanguageprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(BloodprofessorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorCreateAccountLayout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(12, 12, 12)
                        .addGroup(ProfessorCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton3)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        add(ProfessorCreateAccount, "card3");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("E - Learning Platform");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Courses you teach");

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Term", "Class Time", "Term", "No.of Credits", "No.of Modules", "Students registered"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(courseTable);
        if (courseTable.getColumnModel().getColumnCount() > 0) {
            courseTable.getColumnModel().getColumn(0).setResizable(false);
            courseTable.getColumnModel().getColumn(1).setResizable(false);
            courseTable.getColumnModel().getColumn(2).setResizable(false);
            courseTable.getColumnModel().getColumn(3).setResizable(false);
            courseTable.getColumnModel().getColumn(4).setResizable(false);
            courseTable.getColumnModel().getColumn(5).setResizable(false);
            courseTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jToggleButton4.setText("+Add");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("Add new course");

        jLabel17.setText("View / Edit course details");

        jButton2.setText("View / Edit>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Delete course");

        jButton3.setText("Delete>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel19.setText("Add grades to studens");

        jButton4.setText("Add Grades");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("View Profile");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfessorHomepageLayout = new javax.swing.GroupLayout(ProfessorHomepage);
        ProfessorHomepage.setLayout(ProfessorHomepageLayout);
        ProfessorHomepageLayout.setHorizontalGroup(
            ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jToggleButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorHomepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton7)
                        .addGap(197, 197, 197)
                        .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(39, 39, 39)
                                .addComponent(jButton3))
                            .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(39, 39, 39)
                                .addComponent(jButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProfessorHomepageLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3, jButton4});

        ProfessorHomepageLayout.setVerticalGroup(
            ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorHomepageLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton7)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorHomepageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton4)
                        .addComponent(jLabel15))
                    .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfessorHomepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jButton3))
                .addGap(84, 84, 84))
        );

        add(ProfessorHomepage, "card4");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Grades");

        gradestbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student Name", "ID number", "Subject code", "Completed weeks", "Grade points"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(gradestbl);
        if (gradestbl.getColumnModel().getColumnCount() > 0) {
            gradestbl.getColumnModel().getColumn(0).setResizable(false);
            gradestbl.getColumnModel().getColumn(1).setResizable(false);
            gradestbl.getColumnModel().getColumn(3).setResizable(false);
            gradestbl.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton5.setText("Click>>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel21.setText("Click this button to give grade for the selected student:");

        jLabel22.setText("Please enter the Grade:");

        jButton6.setText("Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setText("<<Back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GradesLayout = new javax.swing.GroupLayout(Grades);
        Grades.setLayout(GradesLayout);
        GradesLayout.setHorizontalGroup(
            GradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradesLayout.createSequentialGroup()
                .addGroup(GradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel20))
                    .addGroup(GradesLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GradesLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5))
                    .addGroup(GradesLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(txtGradeP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GradesLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton6)))
                .addGap(58, 58, 58))
        );
        GradesLayout.setVerticalGroup(
            GradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradesLayout.createSequentialGroup()
                .addGroup(GradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel20))
                    .addGroup(GradesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(GradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(GradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtGradeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(24, 24, 24))
        );

        add(Grades, "card5");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Edit Course");

        jLabel24.setText("Course Title:");

        txtsubjectcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubjectcodeActionPerformed(evt);
            }
        });

        jLabel25.setText("Subject Code:");

        jLabel26.setText("Term:");

        jLabel27.setText("Class Time:");

        jLabel28.setText("No.of Credits");

        jLabel30.setText("No.of Modules:");

        jLabel31.setText("Teaching Langiage:");

        jButton8.setText("save");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setText("<<Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditLayout = new javax.swing.GroupLayout(Edit);
        Edit.setLayout(EditLayout);
        EditLayout.setHorizontalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jButton8))
                    .addGroup(EditLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)
                        .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcourseTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtsubjectcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTerm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtclassTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcredits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtModules, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLanguage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(EditLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton11)))
                .addGap(152, 152, 152))
        );

        EditLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLanguage, txtModules, txtTerm, txtclassTime, txtcourseTitle, txtcredits, txtsubjectcode});

        EditLayout.setVerticalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11)
                .addGap(21, 21, 21)
                .addComponent(jLabel23)
                .addGap(30, 30, 30)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtcourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtsubjectcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtclassTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtcredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtModules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(116, 116, 116))
        );

        add(Edit, "card6");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setText("Add new course");

        jLabel33.setText("Course Title:");

        txtsubjectcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubjectcode1ActionPerformed(evt);
            }
        });

        jLabel34.setText("No.of Modules:");

        jLabel35.setText("Subject Code:");

        jLabel36.setText("Teaching Langiage:");

        jLabel37.setText("Term:");

        jButton9.setText("save");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel38.setText("Class Time:");

        jLabel39.setText("No.of Credits");

        jButton12.setText("<<Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCourseLayout = new javax.swing.GroupLayout(AddCourse);
        AddCourse.setLayout(AddCourseLayout);
        AddCourseLayout.setHorizontalGroup(
            AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCourseLayout.createSequentialGroup()
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddCourseLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jButton9))
                    .addGroup(AddCourseLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)
                        .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcourseTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtsubjectcode1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTerm1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtclassTime1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcredits1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtModules1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLanguage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AddCourseLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton12)))
                .addGap(152, 152, 152))
        );
        AddCourseLayout.setVerticalGroup(
            AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCourseLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGap(30, 30, 30)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtcourseTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtsubjectcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtclassTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtcredits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtModules1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtLanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(116, 116, 116))
        );

        add(AddCourse, "card7");

        jLabel16.setText("Last Name :");

        jLabel40.setText("Age :");

        jLabel41.setText("Country :");

        jToggleButton5.setText("Save");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jLabel42.setText("Language :");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel43.setText("View Account");

        jLabel44.setText("Blood Group:");

        AgeprofessorC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeprofessorC1ActionPerformed(evt);
            }
        });

        FnameprofessorC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameprofessorC1ActionPerformed(evt);
            }
        });

        jLabel45.setText("First Name :");

        jLabel48.setText("Username:");

        jLabel49.setText("Password:");

        javax.swing.GroupLayout viewProfileLayout = new javax.swing.GroupLayout(viewProfile);
        viewProfile.setLayout(viewProfileLayout);
        viewProfileLayout.setHorizontalGroup(
            viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProfileLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel48)
                    .addComponent(jLabel16)
                    .addComponent(jLabel45)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel44))
                .addGap(29, 29, 29)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel43)
                        .addComponent(FnameprofessorC1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(LnameprofessorC1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(AgeprofessorC1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(CountryprofessorC1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(LanguageprofessorC1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(BloodprofessorC1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addComponent(jToggleButton5)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
        );
        viewProfileLayout.setVerticalGroup(
            viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProfileLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel43)
                .addGap(31, 31, 31)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(FnameprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(LnameprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(AgeprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(CountryprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(LanguageprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(BloodprofessorC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jToggleButton5)
                .addGap(58, 58, 58))
        );

        add(viewProfile, "card8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        add(jPanel1, "card9");
    }// </editor-fold>//GEN-END:initComponents

    private void AgeprofessorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeprofessorCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeprofessorCActionPerformed

    private void FnameprofessorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameprofessorCActionPerformed
//        ProfessorHomepage.setVisible(false);
//        AddCourse.setVisible(true);
    }//GEN-LAST:event_FnameprofessorCActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
       ProfessorHomepage.setVisible(false);
        AddCourse.setVisible(true);
        
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
    ProfessorLogin.setVisible(false);
    ProfessorCreateAccount.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String username = ProfessorunameL.getText();
        String password = ProfessorpasswordL.getText();
        ProfessorAccount professor = professorDirectory.addProfessorAccount();
        professor.setLoginusername(username);
        professor.setLoginpassword(password);
        for(ProfessorAccount p : professorDirectory.getProfessorList()){
            if(p.getUsername().equals(username) && p.getPassword().equals(password) ){
                   ProfessorLogin.setVisible(false);
                   ProfessorHomepage.setVisible(true);
                   populate();
                   JOptionPane.showMessageDialog(this, "Loged in successfully");
                   return;

            }
        }
        JOptionPane.showMessageDialog(this, "Loged failed");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtsubjectcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubjectcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubjectcodeActionPerformed

    private void txtsubjectcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubjectcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubjectcode1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRowIndex = courseTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Plese select the row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) courseTable.getModel();
        Courses selectedcouCourses =(Courses) model.getValueAt(selectedRowIndex,0);
        txtcourseTitle.setText(String.valueOf(selectedcouCourses.getCourseTitle()));
        txtsubjectcode.setText(String.valueOf(selectedcouCourses.getSubjectCode()));
        txtTerm.setText(String.valueOf(selectedcouCourses.getTerm()) );
        txtclassTime.setText(String.valueOf(selectedcouCourses.getClassTime()));
        txtcredits.setText(String.valueOf(selectedcouCourses.getNumofCredit()));
        txtModules.setText(String.valueOf(selectedcouCourses.getNumofModules()));
        txtLanguage.setText(String.valueOf(selectedcouCourses.getTeachingLanguage()));
        
        Edit.setVisible(true);
        ProfessorHomepage.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Grades.setVisible(true);
        ProfessorHomepage.setVisible(false);
        displaygrades();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String coursetitle = txtcourseTitle1.getText();
        String subjectcode = txtsubjectcode1.getText();
        String term = txtTerm1.getText();
        String classtime = txtclassTime1.getText();
        String credithrs = txtcredits1.getText();
        String modules = txtModules1.getText();
        String language  = txtLanguage1.getText();
        String professoruname = ProfessorunameL.getText();
        Courses course = coursesdirectory.addCourse();
        course.setCourseTitle(coursetitle);
        course.setClassTime(classtime);
        course.setSubjectCode(subjectcode);
        course.setTerm(term);
        course.setNumofModules(modules);
        course.setNumofCredit(credithrs);
        course.setTeachingLanguage(language);
        course.setProfessorname(professoruname);
        course.setStudentsregistered(0);
        JOptionPane.showMessageDialog(this,"Course added successfully");
        populate();
        txtcourseTitle1.setText("");
        txtsubjectcode1.setText("");
        txtTerm1.setText("");
        txtclassTime1.setText("");
        txtcredits1.setText("");
        txtModules1.setText("");
        txtLanguage1.setText("");
        AddCourse.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String courseTitle = txtcourseTitle.getText();
        String subjectcode = txtsubjectcode.getText();
        String term  = txtTerm.getText();
        String classtime = txtclassTime.getText();
        String credits = txtcredits.getText();
        String modules = txtModules.getText();
        String language = txtLanguage.getText();
        Courses course = coursesdirectory.addCourse();
        course.setCourseTitle(courseTitle);
        course.setSubjectCode(subjectcode);
        course.setTerm(term);
        course.setNumofCredit(credits);
        course.setNumofModules(modules);
        course.setTeachingLanguage(language);
        course.setClassTime(classtime);
        Edit.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void AgeprofessorC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeprofessorC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeprofessorC1ActionPerformed

    private void FnameprofessorC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameprofessorC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameprofessorC1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
       
       
       if(FnameprofessorC.getText().isEmpty() || LnameprofessorC.getText().isEmpty() || AgeprofessorC.getText().isEmpty() || CountryprofessorC.getText().isEmpty() || LanguageprofessorC.getText().isEmpty() || BloodprofessorC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter all the fields");
        }
        else{
            String firstName = FnameprofessorC.getText();
            String lastName = LnameprofessorC.getText();
            String age = AgeprofessorC.getText();
            String country = CountryprofessorC.getText();
            String language = LanguageprofessorC.getText();
            String bloodGtp = BloodprofessorC.getText();
            String username = jTextField1.getText();
            String password = jTextField2.getText();
            ProfessorAccount professoraccount = professorDirectory.addProfessorAccount();
            professoraccount.setFirstNamePro(firstName);
            professoraccount.setLastNamePro(lastName);
            professoraccount.setAgePro(age);
            professoraccount.setCountryPro(country);
            professoraccount.setLanguagePro(language);
            professoraccount.setBloodGroupPro(bloodGtp);
            professoraccount.setUsername(username);
            professoraccount.setPassword(password);
        
        JOptionPane.showMessageDialog(this,"Account successfully created");
        }
       FnameprofessorC.setText("");
       LnameprofessorC.setText("");
       AgeprofessorC.setText("");
       CountryprofessorC.setText("");
       LanguageprofessorC.setText("");
       BloodprofessorC.setText("");
       jTextField1.setText("");
       jTextField2.setText("");
       ProfessorCreateAccount.setVisible(false);
       ProfessorLogin.setVisible(true);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int selectedRowIndex = gradestbl.getSelectedRow();
               if(selectedRowIndex<0){
                   JOptionPane.showMessageDialog(this, "Plese select the row");
                   return;
               }
               DefaultTableModel model = (DefaultTableModel) gradestbl.getModel();
               Student selectedstudent =(Student) model.getValueAt(selectedRowIndex, 0);
               for(studentperformance s : performacecatalogue.getperformancelistlist()){
                   if(s.getUername().equals(selectedstudent.getUsername())){
                       
                       s.setGpa(Integer.parseInt(txtGradeP.getText()));
                       if(s.getGpa()>=4){
                        s.setGrade("A");
                    }
                    else if(s.getGpa()<4 &&s.getGpa()>3.3){
                        s.setGrade("B");
                    }
                    else if(s.getGpa()<3.3 &&s.getGpa()>2.3){
                        s.setGrade("C");
                    }
                     else if(s.getGpa()<2.3 &&s.getGpa()>1.3){
                        s.setGrade("D");
                    }
                     else if(s.getGpa()<1.3 &&s.getGpa()>1.0){
                        s.setGrade("E");
                    }
                     else{
                        s.setGrade("F");
                
            }
                   }
               }
               
               displaygrades();
               
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        viewProfile.setVisible(true);
        ProfessorHomepage.setVisible(false);
        displayProfile();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Grades.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Edit.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        AddCourse.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
if(FnameprofessorC.getText().isEmpty() || LnameprofessorC.getText().isEmpty() || AgeprofessorC.getText().isEmpty() || CountryprofessorC.getText().isEmpty() || LanguageprofessorC.getText().isEmpty() || BloodprofessorC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter all the fields");
        }
        else{
            String firstName = FnameprofessorC1.getText();
            String lastName = LnameprofessorC1.getText();
            String age = AgeprofessorC1.getText();
            String country = CountryprofessorC1.getText();
            String language = LanguageprofessorC1.getText();
            String bloodGtp = BloodprofessorC1.getText();
            String username = txtUname.getText();
            String password = txtpassword.getText();
  
            ProfessorAccount professoraccount = professorDirectory.addProfessorAccount();
            professoraccount.setFirstNamePro(firstName);
            professoraccount.setLastNamePro(lastName);
            professoraccount.setAgePro(age);
            professoraccount.setCountryPro(country);
            professoraccount.setLanguagePro(language);
            professoraccount.setBloodGroupPro(bloodGtp);
            professoraccount.setUsername(username);
            professoraccount.setPassword(password);
        
        JOptionPane.showMessageDialog(this,"Profile updated successfully!!");
        }
        viewProfile.setVisible(false);
        ProfessorHomepage.setVisible(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRowIndex = courseTable.getSelectedRow();
               if(selectedRowIndex<0){
                   JOptionPane.showMessageDialog(this, "Plese select the row to delete");
                   return;
               }
               DefaultTableModel model = (DefaultTableModel) courseTable.getModel();
               Courses selectedcourse =(Courses) model.getValueAt(selectedRowIndex,0);
               coursesdirectory.deleteCourse(selectedcourse);

               JOptionPane.showMessageDialog(this, "Course is deleted");
               populate();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int selectedRowIndex = gradestbl.getSelectedRow();
               if(selectedRowIndex<0){
                   JOptionPane.showMessageDialog(this, "Plese select the row");
                   return;
               }
               DefaultTableModel model = (DefaultTableModel) gradestbl.getModel();
               Student selectedstudent =(Student) model.getValueAt(selectedRowIndex, 0);
               for(studentperformance s : performacecatalogue.getperformancelistlist()){
                   if(s.getUername().equals(selectedstudent.getUsername())){
                       
                       txtGradeP.setText(String.valueOf(s.getGpa()));
                   }
               }
               
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddCourse;
    private javax.swing.JTextField AgeprofessorC;
    private javax.swing.JTextField AgeprofessorC1;
    private javax.swing.JTextField BloodprofessorC;
    private javax.swing.JTextField BloodprofessorC1;
    private javax.swing.JTextField CountryprofessorC;
    private javax.swing.JTextField CountryprofessorC1;
    private javax.swing.JPanel Edit;
    private javax.swing.JTextField FnameprofessorC;
    private javax.swing.JTextField FnameprofessorC1;
    private javax.swing.JPanel Grades;
    private javax.swing.JTextField LanguageprofessorC;
    private javax.swing.JTextField LanguageprofessorC1;
    private javax.swing.JTextField LnameprofessorC;
    private javax.swing.JTextField LnameprofessorC1;
    private javax.swing.JPanel ProfessorCreateAccount;
    private javax.swing.JPanel ProfessorHomepage;
    private javax.swing.JPanel ProfessorLogin;
    private javax.swing.JTextField ProfessorpasswordL;
    private javax.swing.JTextField ProfessorunameL;
    private javax.swing.JTable courseTable;
    private javax.swing.JTable gradestbl;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JTextField txtGradeP;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtLanguage1;
    private javax.swing.JTextField txtModules;
    private javax.swing.JTextField txtModules1;
    private javax.swing.JTextField txtTerm;
    private javax.swing.JTextField txtTerm1;
    private javax.swing.JTextField txtUname;
    private javax.swing.JTextField txtclassTime;
    private javax.swing.JTextField txtclassTime1;
    private javax.swing.JTextField txtcourseTitle;
    private javax.swing.JTextField txtcourseTitle1;
    private javax.swing.JTextField txtcredits;
    private javax.swing.JTextField txtcredits1;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtsubjectcode;
    private javax.swing.JTextField txtsubjectcode1;
    private javax.swing.JPanel viewProfile;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        DefaultTableModel model = (DefaultTableModel) courseTable.getModel();
        model.setRowCount(0);
        for( Courses c : coursesdirectory.getCourseList()){
            if(ProfessorunameL.getText().equals(c.getProfessorname())){
                Object[] row = new Object[8];
            row[0] = c;
            row[1] = c.getTerm();
            row[2] = c.getClassTime();
            row[3] = c.getTerm();
            row[4] = c.getNumofCredit();
            row[5] = c.getNumofModules();
            row[6] = c.getStudentsregistered();

            model.addRow(row);
            }
        }
        }
    private void displaygradestest(){
        int selectedRowIndex = courseTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Plese select the row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) courseTable.getModel();
        Courses selectedcouCourses =(Courses) model.getValueAt(selectedRowIndex,0);
        DefaultTableModel model2 = (DefaultTableModel) gradestbl.getModel();
        model2.setRowCount(0);
            for(studentperformance s : performacecatalogue.getperformancelistlist()){
                if(selectedcouCourses.getSubjectCode().equals(s.getSubjectcode())){
                Object[] row = new Object[8];
                row[0] = s;
                row[1] = s.getNUID();
                row[2] = s.getCompletedweeks();
                row[4] = s.getGpa();
                model.addRow(row);
            }
        }
        
        
    }
     private void displaygrades() {
         DefaultTableModel model = (DefaultTableModel) gradestbl.getModel();
        model.setRowCount(0);
        for( choosedcourses c : choosedcatalogue.getChoosedcourseslist()){
            for(Student s : studentCatalogue.getstudentlist()){
                if(c.getuname().equals(s.getUsername()) && c.getProfessoruname().equals(ProfessorunameL.getText())){
                Object[] row = new Object[8];
                row[0] = s;
                row[1] = s.getNuid();
                row[2] = c.getSubjectcode();
                for(studentperformance performance : performacecatalogue.getperformancelistlist()){
                    if(c.getuname().equals(performance.getUername())){
                        row[3] = performance.getCompletedweeks();
                        row[4] = performance.getGpa();
                    }
                }
                
                model.addRow(row);
            }
            }
        }
     }
        

    private void displayProfile() {
        for(ProfessorAccount professor : professorDirectory.getProfessorList()){
            if(professor.getUsername().equals(ProfessorunameL.getText())){
            FnameprofessorC1.setText(professor.getFirstNamePro());
            LnameprofessorC1.setText(professor.getLastNamePro());
            AgeprofessorC1.setText(professor.getAgePro());
            CountryprofessorC1.setText(professor.getCountryPro());
            LanguageprofessorC1.setText(professor.getLanguagePro());
            BloodprofessorC1.setText(professor.getBloodGroupPro());
            txtUname.setText(professor.getUsername());
            txtpassword.setText(professor.getPassword());
            return;
            }
                    
            
        }
        }
}
